name: unit_testing

on:
  push:
    branches-ignore:    
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependency
        run: sudo apt-get update && sudo apt-get install g++
      - name: Configure cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          ./tests
        id: run_tests
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
