name: unit_testing

on:
  push:
    branches-ignore:    
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Configure cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          ./tests

