name: unit_testing

on:
  push:
    branches-ignore:    
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependency
        run: |
          sudo apt-get update && sudo apt-get install g++
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr
          sudo cmake --build build/ --target install 
      - name: Configure cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          make
          ./tests
        id: run_tests
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
