name: unit_testing

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
      - name: Run tests
        run:
          - cmake ..
          - make
          - ./tests
